### ISSUE TITLE
The file downloaded from kapten alloc can't be imported to google calender.

### ISSUE THREAD

**Issue by TheLesso** [bjornregnell/kapten-alloc-web#10]
The file you get when you press download cannot be imported to google calendar. When you try you get "0 of 0 events were imported. Your iCal/CSV file could not be processed." However, it works in Microsoft Outlook, so maybe there is a version error.

**Comment by bjornregnell** [comment]
@TheLesso Thanks for reporting.

@stagrim Do you know what may cause this?

**Comment by stagrim** [comment]
The issue seems to be that `LAST-MODIFIED` and `DTSTAMP` in the `VEVENT` blocks are generated using an incorrect pattern. Months, minutes etc. are not padded with zeroes, which Google calendar does not seem to like. #11 Should fix this

**Comment by TheLesso** [comment]
Looking at it myself, I noticed the error you listed above. But I further noticed that if you run an ics validator on the file returned, it complains about CRLF characters. This seems to come from the fact that the linux that the server is running on uses the LF character for line breaks instead of the CRLF character that the format seems to want and which is the default on Windows. I also tried changing the date to a correct pattern and then importing it into google calander which leads to the same problem. So the CRLF issue also needs to be fixed.

**Comment by bjornregnell** [comment]
@stagrim do you want to update your #11 to fix CRLF problems before I merge? Or maybe @TheLesso wants to fix this in a new PR after I merge #11 ?

**Comment by stagrim** [comment]
Running on a Linux computer, and using my updated fork, I was able to import all KaptenAlloc entries to my Google Calendar. I never got a CRLF issue. Is it a requirement in the iCal format, or only when importing from a Windows computer? @TheLesso Could you try to run my updated fork locally and see if the problem persists? Just clone it, run `sbt fastLinkJS ` in the dir, and then open index-dev.html in your browser.

**Comment by bjornregnell** [comment]
If you dont have sbt @TheLesso 
https://www.scala-sbt.org/

**Comment by bjornregnell** [comment]
Report back here when tested on Windows

**Comment by TheLesso** [comment]
Seemed to work when I tried it on your fork. I Might have changed something else when i was looking around in my files which broke it for me. I am on linux so I have only tried it on windows in a VM but it seems to work there too.

**Comment by bjornregnell** [comment]
Is this ready to merge now?

**Comment by bjornregnell** [comment]
@stagrim @TheLesso Is this ready to merge?

**Comment by TheLesso** [comment]
Yes
